### PR TITLE
Add new metric to 1.9

### PR DESCRIPTION
**Pull request by carlo-colombo**
Signed-off-by: Mark Hender <mhender@pivotal.io>

### CODE REVIEW

**Comment by carlo-colombo** [comment]
We are going to need to add this 1.10 too but we are not shipping this metric with the latest 1.10 we are waiting adding the doc there.

**Comment by ghanna2017** [comment]
Thanks @carlo-colombo

**Comment by davidhiston** [comment]
@ghanna2017 Can the depth metric now be ported to the 1.10 docs as it is now in there as well.

**Comment by ghanna2017** [comment]
@davidhiston OK, will do.

**Pull request merged**
