### PR TITLE
Add entry and screenshots for paid plan checkbox

### PR DESCRIPTION
**Pull request by Jrmcneil**
[#163025062]

Co-authored-by: George Blue <gblue@pivotal.io>

### CODE REVIEW

**Comment by snneji** [comment]
Thanks @Jrmcneil

**Comment by jncd** [comment]
Hi @Jrmcneil and @blgm 
Thanks for the PR with new screenshots.
Are you going to add some additional "conceptual" information to explain what a "paid plan" is?
When, why do you choose a paid plan? What do developers see when they choose to use paid plan? 

Maybe work with @snneji to create some helpful text.  TIA!

**Comment by mkuratczyk** [comment]
It's purely a piece of metadata that customers' operators can use to inform their users (developers pushing to PCF) that a given plan is more expensive (consumes more resources) or will be charged back to their department or something like that. There is no technical difference other than displaying "free" or "paid" when you run `cf marketplace` and similar commands.

**Comment by mkuratczyk** [comment]
Yes, previous versions just defined all plans as free. Some customers requested an option to mark a plan as paid.

**Pull request merged**
