### PR TITLE
Suggest to restart the app instead of restage

### PR DESCRIPTION
**Pull request by nodo**
[#161475021]

Co-authored-by: Michal Kuratczyk <mkuratczyk@pivotal.io>

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @nodo 
Should we cherry-pick these changes back to earlier versions of the docs?
You'll see these in the http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-n/use.html which will be the 1.15 docs in time.

**Comment by nodo** [comment]
Thanks @jncd ! Yes please, would you like me to open the PRs for 1.14, 1.13, and 1.12?

**Comment by jncd** [comment]
Hi @nodo 
I did v1.14 and v1.13 with a cherry-pick.
_Would you PR 1.12?_ It is different from the others, so I got a conflict on the cherry-pick. 
Thanks.

**Comment by nodo** [comment]
Thanks @jncd, I have opened the PR https://github.com/pivotal-cf/docs-rabbitmq-pcf/pull/340

**Pull request merged**
