### PR TITLE
Add release notes for 2.2.0

### PR DESCRIPTION
**Pull request by PujaVad**

### CODE REVIEW

**Comment by RichardJJG** [comment]
Not merging until v2.2 is released

**Comment by RichardJJG** [comment]
Aaaand apparently it's ready for release: https://vmware.slack.com/archives/C84KAKS1Z/p1674049554860759
Merging...

**Comment by RichardJJG** [comment]
@PujaVad, this is the wrong branch to PR to, FYI. The correct branch to target is `master`. I'll cherry-pick your commits now.

**Comment by PujaVad** [comment]
@RichardJJG , apologies, looks like our documentation needs an update then:
image

So the Prs will have to be raised to master for a new minor release?
I remember raising PRs against the minor version branch the last time we had patch releases.

**Comment by RichardJJG** [comment]
@snneji, can you speak to the above? You never told them to deviate from how we've always worked, right?

**Pull request merged**
