### PR TITLE
Update docs after adding BOSH DNS

### PR DESCRIPTION
**Pull request by Jrmcneil**
[#161454249]

Co-authored-by: Andrea Nodari <anodari@pivotal.io>

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @Jrmcneil

**Comment by jncd** [comment]
Hi @Jrmcneil and @nodo 
Thanks for keeping the docs updated! 
As part of the move to BOSH DNS, have you done a quick look through the whole doc? I acked and found this list (screenshot attached).
screen shot 2019-02-26 at 10 21 08 am
... just want to make sure that we make all the needed changes.

**Comment by nodo** [comment]
Thanks @jncd, I will create a story to double check and send another PR if needed

**Comment by jncd** [comment]
Thanks @nodo !
It'll be more obvious to an engineer if more changes are needed.

**Comment by zvance** [comment]
I dont see this reflected in staging - is staging up to date?

**Comment by jncd** [comment]
Hi @zvance 
I think [staging](http://docs-pcf-staging.cfapps.io/rabbitmq-cf/1-n/) is up to date.
The `reference.html` page looks like this PR. 
The `use.html` page looks different from this PR because of more recent PRs that changed the page further. (https://github.com/pivotal-cf/docs-rabbitmq-pcf/commit/4b9046eef419ae5e913627c71a88fa568277a9e9#diff-96ae566453feb0e9569cdfa69b22e8e9 and https://github.com/pivotal-cf/docs-rabbitmq-pcf/commit/2f3cd75a12c9fd5f405b0789c85bd99648d0f81a#diff-96ae566453feb0e9569cdfa69b22e8e9 )

**Pull request merged**
