### PR TITLE
Add documentation for configuring Prometheus via Healthwatch v2.

### PR DESCRIPTION
**Pull request by MirahImage**
Hi docs, this PR is to document the Healthwatch v2 Prometheus and Grafana integration. 

Please cherry-pick this back to 1.19 and 1.20. 

Thanks!

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @MirahImage 
I'll merge, review, cherry-pick and get back to you with any questions.

**Comment by jncd** [comment]
Hi @MirahImage 

Here's the before with questions:
Screen Shot 2020-11-20 at 2 07 47 PM

And my after (which follows house style) but I'm not sure if it's correct.
Screen Shot 2020-11-20 at 2 18 19 PM

I'm out next week but maybe @snneji or @RichardJJG can carry on.

**Comment by MirahImage** [comment]
It looks like we got the wrong link entirely. The link should be to the [Configuration Overview](https://docs.pivotal.io/healthwatch/2-0/common-configurations/configuration-overview.html), and this should be added as an additional scrape job.

**Comment by jncd** [comment]
Hi @MirahImage Much thanks for the correct cross-ref. I've added it now and will submit this story to Samia for acceptance.

**Pull request merged**
